export default Object.freeze({
    // SET_CURRENT_USER: 'auth/SET_CURRENT_USER',
    // SET_CURRENT_USER_FULFILLED: 'auth/SET_CURRENT_USER_FULFILLED',
    // SET_CURRENT_USER_REJECTED: 'auth/SET_CURRENT_USER_REJECTED',

    SET_USER_LOGIN: 'auth/SET_USER_LOGIN',
    SET_USER_LOGIN_FULFILLED: 'auth/SET_USER_LOGIN_FULFILLED',
    SET_USER_LOGIN_REJECTED: 'auth/SET_USER_LOGIN_REJECTED',

    SET_USER_LOGOUT: 'auth/SET_USER_LOGOUT',
    SET_USER_LOGOUT_FULFILLED: 'auth/SET_USER_LOGOUT_FULFILLED',
    SET_USER_LOGOUT_REJECTED: 'auth/SET_USER_LOGOUT_REJETED'
})