export default Object.freeze({
    GET_PROJECTS: 'projects/GET_PROJECTS',
    GET_PROJECTS_FULFILLED: 'projects/GET_PROJECTS_FULFILLED',
    GET_PROJECTS_REJECTED: 'projects/GET_PROJECTS_REJECTED',

    GET_PROJECT: 'projects/GET_PROJECT',
    GET_PROJECT_FULFILLED: 'projects/GET_PROJECT_FULFILLED',
    GET_PROJECT_REJECTED: 'projects/GET_PROJECT_REJECTED',

    CREATE_PROJECT: 'projects/CREATE_PROJECT',
    CREATE_PROJECT_FULFILLED: 'projects/CREATE_PROJECT_FULFILLED',
    CREATE_PROJECT_REJECTED: 'projects/CREATE_PROJECT_REJECTED',

    DELETE_PROJECT: 'projects/DELETE_PROJECT',
    DELETE_PROJECT_FULFILLED: 'projects/DELETE_PROJECT_FULFILLED',
    DELETE_PROJECT_REJECTED: 'projects/DELETE_PROJECT_REJECTED',

    UPDATE_PROJECT: 'projects/UPDATE_PROJECT',
    UPDATE_PROJECT_FULFILLED: 'projects/UPDATE_PROJECT_FULFILLED',
    UPDATE_PROJECT_REJECTED: 'projects/UPDATE_PROJECT_REJECTED'
})