export default Object.freeze({
    GET_OBJECTS: 'objects/GET_OBJECTS',
    GET_OBJECTS_FULFILLED: 'objects/GET_OBJECTS_FULFILLED',
    GET_OBJECTS_REJECTED: 'objects/GET_OBJECTS_REJECTED',

    GET_OBJECT: 'objects/GET_OBJECT',
    GET_OBJECT_FULFILLED: 'objects/GET_OBJECT_FULFILLED',
    GET_OBJECT_REJECTED: 'objects/GET_OBJECT_REJECTED',

    CREATE_OBJECT: 'objects/CREATE_OBJECT',
    CREATE_OBJECT_FULFILLED: 'objects/CREATE_OBJECT_FULFILLED',
    CREATE_OBJECT_REJECTED: 'objects/CREATE_OBJECT_REJECTED',

    DELETE_OBJECT: 'objects/DELETE_OBJECT',
    DELETE_OBJECT_FULFILLED: 'objects/DELETE_OBJECT_FULFILLED',
    DELETE_OBJECT_REJECTED: 'objects/DELETE_OBJECT_REJECTED',

    UPDATE_OBJECT: 'objects/UPDATE_OBJECT',
    UPDATE_OBJECT_FULFILLED: 'objects/UPDATE_OBJECT_FULFILLED',
    UPDATE_OBJECT_REJECTED: 'objects/UPDATE_OBJECT_REJECTED'
})